name: Translations

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Sync

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2
      uses: crowdin/github-action@master
      with:
        upload_sources: true
        upload_translations: true
        download_translations: true
        skip_untranslated_files: true

        source: 'resources/lang/en-GB/*.php'
        translation: 'resources/lang/%locale%/%original_file_name%'

        localization_branch_name: 'translations'
        commit_message: 'New translations'
        pull_request_title: 'New translations'
        pull_request_body: 'https://google.com'
        pull_request_labels: 'Translation'

        project_id: ''
        token: ''
      env:
        GITHUB_TOKEN: ${{ '' }}
